import raw from '../../assets/models_catalogue.json';

/**
 * Typed view over `assets/models_catalogue.json`, which is generated by
 * `tool/generate_models_catalogue.py` at the repository root and bundled, so the
 * app knows its models on a phone that has never been online.
 *
 * Required fields throw rather than default: a catalogue missing a field it
 * depends on should fail loudly in tests, not show a blank card.
 */
export type QuantOption = {
  quant: string;
  fileName: string;
  sizeBytes: number;
  sizeGb?: number;
  sha256?: string;
  qualityNote: string;
  fitsTargetDevice: boolean;
  downloadUrl: string;
};

export type MmprojFile = {
  fileName: string;
  sizeBytes: number;
  sha256?: string;
  downloadUrl: string;
};

export type SamplingDefaults = {
  temperature: number;
  topP: number;
  topK: number;
  repeatPenalty?: number;
};

export type CatalogueModel = {
  id: string;
  displayName: string;
  family: string;
  parameterCount: string;
  sizeClass: string;
  blurb: string;
  hfModelId: string;
  ggufRepoId: string;
  ggufRepoSha?: string;
  ggufRepoUrl: string;
  visionSupported: boolean;
  visionEvidence?: string;
  visionCaveat?: string;
  visionAbsenceNote?: string;
  recommendedContextLength: number;
  maxContextLength: number;
  contextNote?: string;
  /** Hard Wi-Fi-only gate, enforced by the download manager. */
  wifiOnly: boolean;
  highRam: boolean;
  fitsTargetDevice: boolean;
  ramRequirementGb: number;
  warning?: string;
  notes?: string;
  recommendedQuant: string;
  quants: QuantOption[];
  mmproj?: MmprojFile;
  samplingDefaults: SamplingDefaults;
};

export type TargetDevice = { name: string; os: string; ramOptionsGb: number[]; usableRamGb: number };

export type ModelCatalogue = {
  schemaVersion: number;
  targetDevice: TargetDevice;
  models: CatalogueModel[];
};

type Json = Record<string, unknown>;

function req(json: Json, key: string): string {
  const value = json[key];
  if (value === undefined || value === null) {
    throw new Error(`catalogue entry ${String(json.id)} is missing required key "${key}"`);
  }
  return String(value);
}

const str = (v: unknown): string | undefined => (typeof v === 'string' && v.length > 0 ? v : undefined);
const num = (v: unknown, fallback: number): number => (typeof v === 'number' ? v : fallback);
const bool = (v: unknown, fallback: boolean): boolean => (typeof v === 'boolean' ? v : fallback);

function parseQuant(json: Json): QuantOption {
  return {
    quant: req(json, 'quant'),
    fileName: req(json, 'fileName'),
    sizeBytes: num(json.sizeBytes, 0),
    sizeGb: typeof json.sizeGb === 'number' ? json.sizeGb : undefined,
    sha256: str(json.sha256),
    qualityNote: str(json.qualityNote) ?? '',
    fitsTargetDevice: bool(json.fitsTargetDevice, true),
    downloadUrl: req(json, 'downloadUrl'),
  };
}

export function parseModel(json: Json): CatalogueModel {
  const quants = json.quants;
  if (!Array.isArray(quants) || quants.length === 0) {
    throw new Error(`catalogue entry ${String(json.id)} has no quants`);
  }
  const mm = json.mmproj as Json | undefined;
  const sd = (json.samplingDefaults as Json | undefined) ?? {};
  return {
    id: req(json, 'id'),
    displayName: req(json, 'displayName'),
    family: str(json.family) ?? '',
    parameterCount: str(json.parameterCount) ?? '',
    sizeClass: str(json.sizeClass) ?? '',
    blurb: str(json.blurb) ?? '',
    hfModelId: req(json, 'hfModelId'),
    ggufRepoId: req(json, 'ggufRepoId'),
    ggufRepoSha: str(json.ggufRepoSha),
    ggufRepoUrl: req(json, 'ggufRepoUrl'),
    visionSupported: bool(json.visionSupported, false),
    visionEvidence: str(json.visionEvidence),
    visionCaveat: str(json.visionCaveat),
    visionAbsenceNote: str(json.visionAbsenceNote),
    recommendedContextLength: num(json.recommendedContextLength, 4096),
    maxContextLength: num(json.maxContextLength, 4096),
    contextNote: str(json.contextNote),
    wifiOnly: bool(json.wifiOnly, false),
    highRam: bool(json.highRam, false),
    fitsTargetDevice: bool(json.fitsTargetDevice, true),
    ramRequirementGb: num(json.ramRequirementGb, 0),
    warning: str(json.warning),
    notes: str(json.notes),
    recommendedQuant: req(json, 'recommendedQuant'),
    quants: (quants as Json[]).map(parseQuant),
    mmproj: mm
      ? {
          fileName: req(mm, 'fileName'),
          sizeBytes: num(mm.sizeBytes, 0),
          sha256: str(mm.sha256),
          downloadUrl: req(mm, 'downloadUrl'),
        }
      : undefined,
    samplingDefaults: {
      temperature: num(sd.temperature, 0.6),
      topP: num(sd.topP, 0.95),
      topK: num(sd.topK, 20),
      repeatPenalty: typeof sd.repeatPenalty === 'number' ? sd.repeatPenalty : undefined,
    },
  };
}

export function parseCatalogue(json: Json): ModelCatalogue {
  const models = json.models;
  if (!Array.isArray(models)) throw new Error('models_catalogue.json is missing its "models" array');
  const td = (json.targetDevice as Json | undefined) ?? {};
  return {
    schemaVersion: num(json.schemaVersion, 1),
    targetDevice: {
      name: str(td.name) ?? 'Unknown device',
      os: str(td.os) ?? 'Unknown',
      ramOptionsGb: Array.isArray(td.ramOptionsGb) ? (td.ramOptionsGb as number[]) : [],
      usableRamGb: num(td.usableRamGb, 0),
    },
    models: (models as Json[]).map(parseModel),
  };
}

/** The bundled catalogue, parsed once. */
export const catalogue: ModelCatalogue = parseCatalogue(raw as Json);

export function modelById(id: string | null | undefined): CatalogueModel | undefined {
  if (!id) return undefined;
  return catalogue.models.find((m) => m.id === id);
}

export function recommendedQuantOf(model: CatalogueModel): QuantOption {
  return model.quants.find((q) => q.quant === model.recommendedQuant) ?? model.quants[0];
}

/** Everything a download would fetch. Includes the projector so RAM and storage warnings are honest. */
export function totalDownloadBytes(model: CatalogueModel, quant: QuantOption, includeMmproj: boolean): number {
  return quant.sizeBytes + (includeMmproj && model.mmproj ? model.mmproj.sizeBytes : 0);
}
